[env]
TERM = 'alacritty'
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10
bold = { family = "Monospace", style = "Regular" }

builtin_box_drawing = true

[cursor]
blink_interval = 550
unfocused_hollow = true
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 0.7
padding = { x = 15, y = 15 }
dynamic_padding = true
resize_increments = true

[scrolling]
history = 9990
multiplier = 3

[bell]
animation = "linear"
duration = 1
# command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog>
